services:
  db:
    image: mysql:latest
    container_name: rails_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: rails
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3303:3306

  web:
    container_name: web.app
    build:
      context: .
      dockerfile: build/web/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/opt/app
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db
    environment:
      - TZ=Japan
    # pry debugging need these settings
    tty: true
    stdin_open: true